Expense Tracker/Controllers/CategoriesController.cs
using System.Reflection;
using Expense_Tracker.Data;
using Expense_Tracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Expense_Tracker.Controllers
{
    public class CategoriesController : Controller
    {

        //here we need the db context
        private readonly Context _context;

        public CategoriesController(Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await _context.Categories.ToListAsync();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Create([Bind("CategoryId, Title, Icon, Type")] Category category)
        {
            if(ModelState.IsValid)
            {
                _context.Categories.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var category = await _context.Categories.FirstOrDefaultAsync(x => x.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult>Edit(int id, [Bind("CategoryId, Title, Icon, Type")] Category category)
        {
            if(ModelState.IsValid)
            {
                _context.Update(category);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var category = await _context.Categories.FirstOrDefaultAsync(x => x.CategoryId == id);
            return View(category);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }


    }
}

Expense Tracker/Controllers/DashboardController.cs
using Expense_Tracker.Data;
using Expense_Tracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Expense_Tracker.Controllers
{
    public class DashboardController : Controller
    {
        private readonly Context _context;
        public DashboardController(Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            //actions in the last 30 days
            DateTime StartDate = DateTime.Today.AddDays(-30);
            DateTime EndDate = DateTime.Today;
            List<Transaction> SelectedTransactions = await  _context.Transactions
                .Include(x => x.Category)
                .Where(y => y.Date >= StartDate && y.Date <= EndDate)
                .ToListAsync();

            //total income
            double TotalIncome = SelectedTransactions
                .Where(t => t.Category.Type == "Income")
                .Sum(t => t.Amount);
            ViewBag.TotalIncome = TotalIncome.ToString();

            //total expense
            double TotalExpense = SelectedTransactions
                .Where(t => t.Category.Type == "Expense")
                .Sum(t => t.Amount);
            ViewBag.TotalExpense = TotalExpense.ToString();

            //balance
            double TotalBalance = TotalIncome - TotalExpense;
            ViewBag.TotalBalance = TotalBalance.ToString();

            //doughnut chart - expense by category
            var expenceByCategory = SelectedTransactions
                .Where(t => t.Category.Type == "Expense")
                .GroupBy(t => t.Category.Title)
                .Select(group => new
                {
                    Category = group.Key,
                    TotalAmount = group.Sum(t => t.Amount)
                }).ToList();

            //prepare data for the doughnut chart
            ViewBag.ExpenseCategories = expenceByCategory.Select(e=>e.Category).ToList(); //labels
            ViewBag.ExpenseAmounts = expenceByCategory.Select(e => e.TotalAmount).ToList(); //data



            //line chart - income vs expense
            //income

            var dailyIncome = SelectedTransactions
                .Where(t=>t.Category.Type=="Income")
                .GroupBy(t=>t.Date.Date)
                .Select(group=> new
                {
                    Date = group.Key,
                    TotalAmount = group.Sum(t => t.Amount)
                }) .ToList();

            var dailyExpense = SelectedTransactions
                .Where(t => t.Category.Type == "Expense")
                .GroupBy(t => t.Date.Date)
                .Select(group => new
                { 
                    Date = group.Key,
                    TotalAmount = group.Sum(t=>t.Amount)
                
                }).ToList();

            //generate a list for the last 30 days
            var last30Days = Enumerable.Range(0, 30)
                .Select(i => DateTime.Today.AddDays(-i))
                .ToList();
            //prepare data for the line chart
            var incomeData = last30Days
                .Select(date => dailyIncome.FirstOrDefault(d => d.Date == date)?.TotalAmount ?? 0)
                .ToList();

            var expenseData = last30Days
                .Select(date => dailyExpense.FirstOrDefault(d => d.Date == date)?.TotalAmount ?? 0)
                .ToList();

            ViewBag.Dates = last30Days.Select(d=>d.ToString("dd/MM/yyyy")).ToList();//x-axis
            ViewBag.IncomeData = incomeData; //y-axis
            ViewBag.ExpenseData = expenseData; //y-axis

            return View();
        }
    }
}

Expense Tracker/Controllers/TransactionsController.cs
using Expense_Tracker.Models;
using Expense_Tracker.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Expense_Tracker.Controllers
{
    public class TransactionsController : Controller
    {
        //here we need the dbContext
        private readonly Context _context;
        public TransactionsController(Context context)
        {
            _context = context;
        }
      public async Task<IActionResult> Index()
        {
            var transactions = await _context.Transactions
                .Include(t=>t.Category)
                .ToListAsync();
            return View(transactions);
        }

        public IActionResult Create()
        {
            ViewData["Categories"] = new SelectList(_context.Categories, "CategoryId", "Title");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("TransactionId, CategoryId, Amount, Note, Date")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                _context.Transactions.Add(transaction);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            //re-populating the dropdown list when the model state is invalid
            ViewData["Categories"] = new SelectList(_context.Categories, "CategoryId", "Title");
            return View(transaction);
        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Categories"] = new SelectList(_context.Categories, "CategoryId", "Title");
            var transaction = await _context.Transactions.FirstOrDefaultAsync(x => x.TransactionId == id);
            if (transaction == null)
            {
                return NotFound();
            }
            return View(transaction);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id ,[Bind("TransactionId, CategoryId, Amount, Note,Date")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                _context.Update(transaction);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            //re-populating the dropdown list when the model state is invalid
            ViewData["Categories"] = new SelectList(_context.Categories, "CategoryId", "Title");
            return View(transaction);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var transaction = await _context.Transactions.FirstOrDefaultAsync(x => x.TransactionId == id);            
            return View(transaction);
        }
        // This method is called when the user confirms the deletion
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transaction = await _context.Transactions.FindAsync(id);
            if (transaction != null)
            {
                _context.Transactions.Remove(transaction);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

    }

}

Expense Tracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Expense Tracker</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Expense_Tracker.styles.css" asp-append-version="true" />
    @*font awesome icons*@
    <script src="https://kit.fontawesome.com/75a49f2bb8.js" crossorigin="anonymous"></script>
    @*chart.js*@
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">Expense Tracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Expense Tracker
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>